### ISSUE TITLE
checksum mismatch for v0.10.0 release

### ISSUE THREAD

**Issue by kevinburke** [charmbracelet/glamour#483]
### Description

If you set GOPROXY=direct and then attempt to download this project, you will get an error that looks like this:

	github.com/charmbracelet/glamour: github.com/charmbracelet/glamour@v0.10.0: verifying module: checksum mismatch
	downloaded: h1:41/IYxsmIpaBjkMXjrjLwsHDBlucd5at6tY5n2r/qn4=
	sum.golang.org: h1:MtZvfwsYCx8jEPFJm3rIBFIMZUfUJ765oX8V6kXldcY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

Typically, this happens when you push a tag, Go module cache caches that tag, and then you push different contents to the same tag.

The simplest fix would be to push a new Git tag and then not change it at all.

### Version

v0.10.0

**Comment by Khechani** [comment]
[] github.com/charmbracelet/glamour: github.com/charmbracelet/glamour@v0.10.0: verifying module: checksum mismatch
downloaded: h1:41/IYxsmIpaBjkMXjrjLwsHDBlucd5at6tY5n2r/qn4=
sum.golang.org: h1:MtZvfwsYCx8jEPFJm3rIBFIMZUfUJ765oX8V6kXldcY=(url)

**Comment by larsks** [comment]
I see that it's possible to work around this by adding problematic modules to `GONOSUBDMB`:

```
GONOSUMDB=github.com/charmbracelet/glamour,github.com/charmbracelet/x go mod tidy
```

Of course, this is a terrible solution, because it completely bypasses the checksum security, but it will allow you to build a project.

**Comment by lucasl0st** [comment]
This looks like the same git-lfs issue found here: https://github.com/charmbracelet/x/issues/651#issuecomment-3577600122
Which was fixed here: https://github.com/charmbracelet/x/pull/661

Maybe we need something similar for the resources here https://github.com/charmbracelet/glamour/tree/main/styles

**Comment by andrinoff** [comment]
@lucasl0st, and everyone

Sorry for this issue not having a reply sooner.

I am currently testing this and it works fine, but the last comment was left a month ago, what is the issue right now?

P.S. Due to v2, the package name has changed (now, `charm.land/glamour/v2`)

**Comment by skinner-m-c** [comment]
I think because there are newer versions than the version referenced here that this can be closed unless there is some strong reason to support the v0.10.x line so long as other software by Charm is not using 0.10.0, but a newer version.

**Comment by kevinburke** [comment]
I'm still seeing this issue with the v2 changes unfortunately.

`go get`/`go mod tidy` fails with a checksum mismatch when `GOPROXY` includes
`direct`:

```
go: charm.land/glamour/v2@v2.0.1: verifying module: checksum mismatch
	downloaded: h1:Vx2F81a4SBR5/IqAkDyeZ3mfuT7u+9AYxeXQ+J1n2Wc=
	sum.golang.org: h1:xl+r00A4aJWU0z8fgwKd9fQQ4rsphqGUzuEiXZP5n+c=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

Fetching the identical version through the module proxy instead of direct
VCS resolution succeeds and matches sumdb cleanly:

```
GOPROXY=https://proxy.golang.org go get charm.land/glamour/v2@v2.0.1   # succeeds, matches sumdb
GOPROXY=direct go get charm.land/glamour/v2@v2.0.1                     # checksum mismatch above
```

**Comment by kevinburke** [comment]
Typically this means you have a release process that pushes a git tag and then at some point you push different contents to the same tag.

**Comment by andrinoff** [comment]
This is due to your PC having the incorrect cache. To fix:

```sh
go clean -modcache
GOPROXY=https://proxy.golang.org,direct go mod download
```

Also, could be useful to run:

```sh

GOMODCACHE=$(mktemp -d) GOPROXY=direct GOSUMDB=off \
  go mod download -json charm.land/glamour/v2@v2.0.1 | grep '"Sum"'

```

(the result should be `h1:xl+r00A4aJWU0z8fgwKd9fQQ4rsphqGUzuEiXZP5n+c=`)

**Comment by andrinoff** [comment]
Closing this as I believe this issue is sorted, but if not let me know and we can reopen.
